CREATE TABLE IF NOT EXISTS rentals (
    id INT NOT NULL AUTO_INCREMENT,
    start_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_date DATETIME,
    status VARCHAR(50) NOT NULL,
    price FLOAT NOT NULL,
    payment_status VARCHAR(255) NOT NULL DEFAULT 'unpaid',

    PRIMARY KEY (id)
);