version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '..:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '65000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '..:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'

    mysql:
        image: mysql:latest
        container_name: my-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: container
            MYSQL_USER: user
            MYSQL_PASSWORD: 12345
            MYSQL_SSL_CA: ""
        ports:
            - '3306:3306'
        volumes:
            - ./var/mysql-data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: my-mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '8080:80'

#    mongo:
#        image: mongo:latest
#        container_name: my-mongo
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: root
#        ports:
#            - '27017:27017'
#        volumes:
#            - ./var/mongo-data:/data/db
#
#    mongo-express:
#        image: mongo-express:latest
#        container_name: mongo-express
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: root
#            ME_CONFIG_MONGODB_ADMINPASSWORD: root
#            ME_CONFIG_MONGODB_SERVER: my-mongo
#            ME_CONFIG_BASICAUTH_USERNAME: admin
#            ME_CONFIG_BASICAUTH_PASSWORD: 12345
#        ports:
#            - '9090:8081'
#        depends_on:
#            - mongo


    composer:
        image: composer:latest
        working_dir: /application
        volumes:
            - '..:/application'
        command: install
